export const WORLD_CURRENCIES = [
  { code: "USD", name: "US Dollar", emoji: "🇺🇸" },
  { code: "EUR", name: "Euro", emoji: "🇪🇺" },
  { code: "GBP", name: "British Pound", emoji: "🇬🇧" },
  { code: "JPY", name: "Japanese Yen", emoji: "🇯🇵" },
  { code: "CAD", name: "Canadian Dollar", emoji: "🇨🇦" },
  { code: "AUD", name: "Australian Dollar", emoji: "🇦🇺" },
  { code: "CHF", name: "Swiss Franc", emoji: "🇨🇭" },
  { code: "CNY", name: "Chinese Yuan", emoji: "🇨🇳" },
  { code: "INR", name: "Indian Rupee", emoji: "🇮🇳" },
  { code: "BRL", name: "Brazilian Real", emoji: "🇧🇷" },
  { code: "RUB", name: "Russian Ruble", emoji: "🇷🇺" },
  { code: "KRW", name: "South Korean Won", emoji: "🇰🇷" },
  { code: "MXN", name: "Mexican Peso", emoji: "🇲🇽" },
  { code: "SGD", name: "Singapore Dollar", emoji: "🇸🇬" },
  { code: "HKD", name: "Hong Kong Dollar", emoji: "🇭🇰" },
  { code: "NOK", name: "Norwegian Krone", emoji: "🇳🇴" },
  { code: "SEK", name: "Swedish Krona", emoji: "🇸🇪" },
  { code: "DKK", name: "Danish Krone", emoji: "🇩🇰" },
  { code: "PLN", name: "Polish Zloty", emoji: "🇵🇱" },
  { code: "CZK", name: "Czech Koruna", emoji: "🇨🇿" },
  { code: "HUF", name: "Hungarian Forint", emoji: "🇭🇺" },
  { code: "RON", name: "Romanian Leu", emoji: "🇷🇴" },
  { code: "BGN", name: "Bulgarian Lev", emoji: "🇧🇬" },
  { code: "HRK", name: "Croatian Kuna", emoji: "🇭🇷" },
  { code: "TRY", name: "Turkish Lira", emoji: "🇹🇷" },
  { code: "ILS", name: "Israeli Shekel", emoji: "🇮🇱" },
  { code: "AED", name: "UAE Dirham", emoji: "🇦🇪" },
  { code: "SAR", name: "Saudi Riyal", emoji: "🇸🇦" },
  { code: "QAR", name: "Qatari Riyal", emoji: "🇶🇦" },
  { code: "KWD", name: "Kuwaiti Dinar", emoji: "🇰🇼" },
  { code: "BHD", name: "Bahraini Dinar", emoji: "🇧🇭" },
  { code: "OMR", name: "Omani Rial", emoji: "🇴🇲" },
  { code: "JOD", name: "Jordanian Dinar", emoji: "🇯🇴" },
  { code: "LBP", name: "Lebanese Pound", emoji: "🇱🇧" },
  { code: "EGP", name: "Egyptian Pound", emoji: "🇪🇬" },
  { code: "MAD", name: "Moroccan Dirham", emoji: "🇲🇦" },
  { code: "TND", name: "Tunisian Dinar", emoji: "🇹🇳" },
  { code: "DZD", name: "Algerian Dinar", emoji: "🇩🇿" },
  { code: "LYD", name: "Libyan Dinar", emoji: "🇱🇾" },
  { code: "SDG", name: "Sudanese Pound", emoji: "🇸🇩" },
  { code: "ETB", name: "Ethiopian Birr", emoji: "🇪🇹" },
  { code: "KES", name: "Kenyan Shilling", emoji: "🇰🇪" },
  { code: "UGX", name: "Ugandan Shilling", emoji: "🇺🇬" },
  { code: "TZS", name: "Tanzanian Shilling", emoji: "🇹🇿" },
  { code: "RWF", name: "Rwandan Franc", emoji: "🇷🇼" },
  { code: "ZAR", name: "South African Rand", emoji: "🇿🇦" },
  { code: "BWP", name: "Botswana Pula", emoji: "🇧🇼" },
  { code: "NAD", name: "Namibian Dollar", emoji: "🇳🇦" },
  { code: "SZL", name: "Swazi Lilangeni", emoji: "🇸🇿" },
  { code: "LSL", name: "Lesotho Loti", emoji: "🇱🇸" },
  { code: "MWK", name: "Malawian Kwacha", emoji: "🇲🇼" },
  { code: "ZMW", name: "Zambian Kwacha", emoji: "🇿🇲" },
  { code: "ZWL", name: "Zimbabwean Dollar", emoji: "🇿🇼" },
  { code: "MZN", name: "Mozambican Metical", emoji: "🇲🇿" },
  { code: "MGA", name: "Malagasy Ariary", emoji: "🇲🇬" },
  { code: "MUR", name: "Mauritian Rupee", emoji: "🇲🇺" },
  { code: "SCR", name: "Seychellois Rupee", emoji: "🇸🇨" },
  { code: "KMF", name: "Comorian Franc", emoji: "🇰🇲" },
  { code: "DJF", name: "Djiboutian Franc", emoji: "🇩🇯" },
  { code: "SOS", name: "Somali Shilling", emoji: "🇸🇴" },
  { code: "ERN", name: "Eritrean Nakfa", emoji: "🇪🇷" },
  { code: "CDF", name: "Congolese Franc", emoji: "🇨🇩" },
  { code: "AOA", name: "Angolan Kwanza", emoji: "🇦🇴" },
  { code: "CVE", name: "Cape Verdean Escudo", emoji: "🇨🇻" },
  { code: "GNF", name: "Guinean Franc", emoji: "🇬🇳" },
  { code: "GMD", name: "Gambian Dalasi", emoji: "🇬🇲" },
  { code: "SLL", name: "Sierra Leonean Leone", emoji: "🇸🇱" },
  { code: "LRD", name: "Liberian Dollar", emoji: "🇱🇷" },
  { code: "GHS", name: "Ghanaian Cedi", emoji: "🇬🇭" },
  { code: "NGN", name: "Nigerian Naira", emoji: "🇳🇬" },
  { code: "BIF", name: "Burundian Franc", emoji: "🇧🇮" },
  { code: "CFA", name: "CFA Franc", emoji: "🌍" },
  { code: "XOF", name: "West African CFA Franc", emoji: "🌍" },
  { code: "XAF", name: "Central African CFA Franc", emoji: "🌍" },
  // Adding more major currencies
  { code: "THB", name: "Thai Baht", emoji: "🇹🇭" },
  { code: "MYR", name: "Malaysian Ringgit", emoji: "🇲🇾" },
  { code: "IDR", name: "Indonesian Rupiah", emoji: "🇮🇩" },
  { code: "PHP", name: "Philippine Peso", emoji: "🇵🇭" },
  { code: "VND", name: "Vietnamese Dong", emoji: "🇻🇳" },
  { code: "LAK", name: "Lao Kip", emoji: "🇱🇦" },
  { code: "KHR", name: "Cambodian Riel", emoji: "🇰🇭" },
  { code: "MMK", name: "Myanmar Kyat", emoji: "🇲🇲" },
  { code: "BDT", name: "Bangladeshi Taka", emoji: "🇧🇩" },
  { code: "PKR", name: "Pakistani Rupee", emoji: "🇵🇰" },
  { code: "LKR", name: "Sri Lankan Rupee", emoji: "🇱🇰" },
  { code: "NPR", name: "Nepalese Rupee", emoji: "🇳🇵" },
  { code: "BTN", name: "Bhutanese Ngultrum", emoji: "🇧🇹" },
  { code: "MVR", name: "Maldivian Rufiyaa", emoji: "🇲🇻" },
  { code: "AFN", name: "Afghan Afghani", emoji: "🇦🇫" },
  { code: "IRR", name: "Iranian Rial", emoji: "🇮🇷" },
  { code: "IQD", name: "Iraqi Dinar", emoji: "🇮🇶" },
  { code: "SYP", name: "Syrian Pound", emoji: "🇸🇾" },
  { code: "YER", name: "Yemeni Rial", emoji: "🇾🇪" },
  { code: "UZS", name: "Uzbekistani Som", emoji: "🇺🇿" },
  { code: "KZT", name: "Kazakhstani Tenge", emoji: "🇰🇿" },
  { code: "KGS", name: "Kyrgyzstani Som", emoji: "🇰🇬" },
  { code: "TJS", name: "Tajikistani Somoni", emoji: "🇹🇯" },
  { code: "TMT", name: "Turkmenistani Manat", emoji: "🇹🇲" },
  { code: "AZN", name: "Azerbaijani Manat", emoji: "🇦🇿" },
  { code: "GEL", name: "Georgian Lari", emoji: "🇬🇪" },
  { code: "AMD", name: "Armenian Dram", emoji: "🇦🇲" },
  { code: "BYN", name: "Belarusian Ruble", emoji: "🇧🇾" },
  { code: "UAH", name: "Ukrainian Hryvnia", emoji: "🇺🇦" },
  { code: "MDL", name: "Moldovan Leu", emoji: "🇲🇩" },
  { code: "ALL", name: "Albanian Lek", emoji: "🇦🇱" },
  { code: "MKD", name: "Macedonian Denar", emoji: "🇲🇰" },
  { code: "RSD", name: "Serbian Dinar", emoji: "🇷🇸" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", emoji: "🇧🇦" },
  { code: "EUR", name: "Euro (Montenegro)", emoji: "🇲🇪" },
  { code: "EUR", name: "Euro (Kosovo)", emoji: "🇽🇰" },
  // Americas
  { code: "ARS", name: "Argentine Peso", emoji: "🇦🇷" },
  { code: "BOB", name: "Bolivian Boliviano", emoji: "🇧🇴" },
  { code: "CLP", name: "Chilean Peso", emoji: "🇨🇱" },
  { code: "COP", name: "Colombian Peso", emoji: "🇨🇴" },
  { code: "PEN", name: "Peruvian Sol", emoji: "🇵🇪" },
  { code: "UYU", name: "Uruguayan Peso", emoji: "🇺🇾" },
  { code: "PYG", name: "Paraguayan Guarani", emoji: "🇵🇾" },
  { code: "VES", name: "Venezuelan Bolívar", emoji: "🇻🇪" },
  { code: "GYD", name: "Guyanese Dollar", emoji: "🇬🇾" },
  { code: "SRD", name: "Surinamese Dollar", emoji: "🇸🇷" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", emoji: "🇹🇹" },
  { code: "JMD", name: "Jamaican Dollar", emoji: "🇯🇲" },
  { code: "BBD", name: "Barbadian Dollar", emoji: "🇧🇧" },
  { code: "BSD", name: "Bahamian Dollar", emoji: "🇧🇸" },
  { code: "BZD", name: "Belize Dollar", emoji: "🇧🇿" },
  { code: "GTQ", name: "Guatemalan Quetzal", emoji: "🇬🇹" },
  { code: "HNL", name: "Honduran Lempira", emoji: "🇭🇳" },
  { code: "NIO", name: "Nicaraguan Córdoba", emoji: "🇳🇮" },
  { code: "CRC", name: "Costa Rican Colón", emoji: "🇨🇷" },
  { code: "PAB", name: "Panamanian Balboa", emoji: "🇵🇦" },
  { code: "DOP", name: "Dominican Peso", emoji: "🇩🇴" },
  { code: "HTG", name: "Haitian Gourde", emoji: "🇭🇹" },
  { code: "CUP", name: "Cuban Peso", emoji: "🇨🇺" },
  // Oceania
  { code: "NZD", name: "New Zealand Dollar", emoji: "🇳🇿" },
  { code: "FJD", name: "Fijian Dollar", emoji: "🇫🇯" },
  { code: "PGK", name: "Papua New Guinean Kina", emoji: "🇵🇬" },
  { code: "SBD", name: "Solomon Islands Dollar", emoji: "🇸🇧" },
  { code: "VUV", name: "Vanuatu Vatu", emoji: "🇻🇺" },
  { code: "WST", name: "Samoan Tala", emoji: "🇼🇸" },
  { code: "TOP", name: "Tongan Paʻanga", emoji: "🇹🇴" },
  { code: "XPF", name: "CFP Franc", emoji: "🇵🇫" },
]

export function getCurrencyWithCRED(currencyCode: string) {
  const currency = WORLD_CURRENCIES.find((c) => c.code === currencyCode)
  if (!currency) return null

  return {
    ...currency,
    credCode: `${currencyCode}-CRED`,
    credName: `${currency.name} CRED`,
  }
}

export async function getExchangeRates() {
  try {
    // Using a free exchange rate API
    const response = await fetch("https://api.exchangerate-api.com/v4/latest/USD")
    const data = await response.json()
    return data.rates
  } catch (error) {
    console.error("Failed to fetch exchange rates:", error)
    // Return default rates if API fails
    return { USD: 1, EUR: 0.85, GBP: 0.73, CAD: 1.25, JPY: 110 }
  }
}
