interface Currency {
  id: string
  name: string
  code: string
  symbol: string
  country: string
  flag: string
  credValue: number
  isActive: boolean
}

export const currencies: Currency[] = [
  // Major World Currencies
  {
    id: "1",
    name: "United States Dollar",
    code: "USD",
    symbol: "$",
    country: "United States",
    flag: "🇺🇸",
    credValue: 1.0,
    isActive: true,
  },
  {
    id: "2",
    name: "Euro",
    code: "EUR",
    symbol: "€",
    country: "European Union",
    flag: "🇪🇺",
    credValue: 1.08,
    isActive: true,
  },
  {
    id: "3",
    name: "British Pound Sterling",
    code: "GBP",
    symbol: "£",
    country: "United Kingdom",
    flag: "🇬🇧",
    credValue: 1.27,
    isActive: true,
  },
  {
    id: "4",
    name: "Japanese Yen",
    code: "JPY",
    symbol: "¥",
    country: "Japan",
    flag: "🇯🇵",
    credValue: 0.0067,
    isActive: true,
  },
  {
    id: "5",
    name: "Swiss Franc",
    code: "CHF",
    symbol: "Fr",
    country: "Switzerland",
    flag: "🇨🇭",
    credValue: 1.12,
    isActive: true,
  },
  {
    id: "6",
    name: "Canadian Dollar",
    code: "CAD",
    symbol: "C$",
    country: "Canada",
    flag: "🇨🇦",
    credValue: 0.74,
    isActive: true,
  },
  {
    id: "7",
    name: "Australian Dollar",
    code: "AUD",
    symbol: "A$",
    country: "Australia",
    flag: "🇦🇺",
    credValue: 0.65,
    isActive: true,
  },
  {
    id: "8",
    name: "New Zealand Dollar",
    code: "NZD",
    symbol: "NZ$",
    country: "New Zealand",
    flag: "🇳🇿",
    credValue: 0.6,
    isActive: true,
  },
  {
    id: "9",
    name: "Chinese Yuan",
    code: "CNY",
    symbol: "¥",
    country: "China",
    flag: "🇨🇳",
    credValue: 0.14,
    isActive: true,
  },
  {
    id: "10",
    name: "Hong Kong Dollar",
    code: "HKD",
    symbol: "HK$",
    country: "Hong Kong",
    flag: "🇭🇰",
    credValue: 0.13,
    isActive: true,
  },

  // Asian Currencies
  {
    id: "11",
    name: "Singapore Dollar",
    code: "SGD",
    symbol: "S$",
    country: "Singapore",
    flag: "🇸🇬",
    credValue: 0.74,
    isActive: true,
  },
  {
    id: "12",
    name: "South Korean Won",
    code: "KRW",
    symbol: "₩",
    country: "South Korea",
    flag: "🇰🇷",
    credValue: 0.00076,
    isActive: true,
  },
  {
    id: "13",
    name: "Indian Rupee",
    code: "INR",
    symbol: "₹",
    country: "India",
    flag: "🇮🇳",
    credValue: 0.012,
    isActive: true,
  },
  {
    id: "14",
    name: "Thai Baht",
    code: "THB",
    symbol: "฿",
    country: "Thailand",
    flag: "🇹🇭",
    credValue: 0.028,
    isActive: true,
  },
  {
    id: "15",
    name: "Malaysian Ringgit",
    code: "MYR",
    symbol: "RM",
    country: "Malaysia",
    flag: "🇲🇾",
    credValue: 0.22,
    isActive: true,
  },
  {
    id: "16",
    name: "Indonesian Rupiah",
    code: "IDR",
    symbol: "Rp",
    country: "Indonesia",
    flag: "🇮🇩",
    credValue: 0.000066,
    isActive: true,
  },
  {
    id: "17",
    name: "Philippine Peso",
    code: "PHP",
    symbol: "₱",
    country: "Philippines",
    flag: "🇵🇭",
    credValue: 0.018,
    isActive: true,
  },
  {
    id: "18",
    name: "Vietnamese Dong",
    code: "VND",
    symbol: "₫",
    country: "Vietnam",
    flag: "🇻🇳",
    credValue: 0.000041,
    isActive: true,
  },
  {
    id: "19",
    name: "Taiwan Dollar",
    code: "TWD",
    symbol: "NT$",
    country: "Taiwan",
    flag: "🇹🇼",
    credValue: 0.031,
    isActive: true,
  },
  {
    id: "20",
    name: "Pakistani Rupee",
    code: "PKR",
    symbol: "₨",
    country: "Pakistan",
    flag: "🇵🇰",
    credValue: 0.0036,
    isActive: true,
  },

  // Middle Eastern Currencies
  {
    id: "21",
    name: "Saudi Riyal",
    code: "SAR",
    symbol: "﷼",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    credValue: 0.27,
    isActive: true,
  },
  {
    id: "22",
    name: "UAE Dirham",
    code: "AED",
    symbol: "د.إ",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    credValue: 0.27,
    isActive: true,
  },
  {
    id: "23",
    name: "Qatari Riyal",
    code: "QAR",
    symbol: "﷼",
    country: "Qatar",
    flag: "🇶🇦",
    credValue: 0.27,
    isActive: true,
  },
  {
    id: "24",
    name: "Kuwaiti Dinar",
    code: "KWD",
    symbol: "د.ك",
    country: "Kuwait",
    flag: "🇰🇼",
    credValue: 3.25,
    isActive: true,
  },
  {
    id: "25",
    name: "Bahraini Dinar",
    code: "BHD",
    symbol: ".د.ب",
    country: "Bahrain",
    flag: "🇧🇭",
    credValue: 2.65,
    isActive: true,
  },
  {
    id: "26",
    name: "Omani Rial",
    code: "OMR",
    symbol: "﷼",
    country: "Oman",
    flag: "🇴🇲",
    credValue: 2.6,
    isActive: true,
  },
  {
    id: "27",
    name: "Jordanian Dinar",
    code: "JOD",
    symbol: "د.ا",
    country: "Jordan",
    flag: "🇯🇴",
    credValue: 1.41,
    isActive: true,
  },
  {
    id: "28",
    name: "Lebanese Pound",
    code: "LBP",
    symbol: "£",
    country: "Lebanon",
    flag: "🇱🇧",
    credValue: 0.000066,
    isActive: true,
  },
  {
    id: "29",
    name: "Israeli Shekel",
    code: "ILS",
    symbol: "₪",
    country: "Israel",
    flag: "🇮🇱",
    credValue: 0.27,
    isActive: true,
  },
  {
    id: "30",
    name: "Turkish Lira",
    code: "TRY",
    symbol: "₺",
    country: "Turkey",
    flag: "🇹🇷",
    credValue: 0.034,
    isActive: true,
  },

  // European Currencies
  {
    id: "31",
    name: "Norwegian Krone",
    code: "NOK",
    symbol: "kr",
    country: "Norway",
    flag: "🇳🇴",
    credValue: 0.092,
    isActive: true,
  },
  {
    id: "32",
    name: "Swedish Krona",
    code: "SEK",
    symbol: "kr",
    country: "Sweden",
    flag: "🇸🇪",
    credValue: 0.091,
    isActive: true,
  },
  {
    id: "33",
    name: "Danish Krone",
    code: "DKK",
    symbol: "kr",
    country: "Denmark",
    flag: "🇩🇰",
    credValue: 0.14,
    isActive: true,
  },
  {
    id: "34",
    name: "Polish Zloty",
    code: "PLN",
    symbol: "zł",
    country: "Poland",
    flag: "🇵🇱",
    credValue: 0.24,
    isActive: true,
  },
  {
    id: "35",
    name: "Czech Koruna",
    code: "CZK",
    symbol: "Kč",
    country: "Czech Republic",
    flag: "🇨🇿",
    credValue: 0.043,
    isActive: true,
  },
  {
    id: "36",
    name: "Hungarian Forint",
    code: "HUF",
    symbol: "Ft",
    country: "Hungary",
    flag: "🇭🇺",
    credValue: 0.0027,
    isActive: true,
  },
  {
    id: "37",
    name: "Romanian Leu",
    code: "RON",
    symbol: "lei",
    country: "Romania",
    flag: "🇷🇴",
    credValue: 0.22,
    isActive: true,
  },
  {
    id: "38",
    name: "Bulgarian Lev",
    code: "BGN",
    symbol: "лв",
    country: "Bulgaria",
    flag: "🇧🇬",
    credValue: 0.55,
    isActive: true,
  },
  {
    id: "39",
    name: "Croatian Kuna",
    code: "HRK",
    symbol: "kn",
    country: "Croatia",
    flag: "🇭🇷",
    credValue: 0.14,
    isActive: true,
  },
  {
    id: "40",
    name: "Russian Ruble",
    code: "RUB",
    symbol: "₽",
    country: "Russia",
    flag: "🇷🇺",
    credValue: 0.011,
    isActive: true,
  },

  // African Currencies
  {
    id: "41",
    name: "South African Rand",
    code: "ZAR",
    symbol: "R",
    country: "South Africa",
    flag: "🇿🇦",
    credValue: 0.053,
    isActive: true,
  },
  {
    id: "42",
    name: "Nigerian Naira",
    code: "NGN",
    symbol: "₦",
    country: "Nigeria",
    flag: "🇳🇬",
    credValue: 0.0012,
    isActive: true,
  },
  {
    id: "43",
    name: "Kenyan Shilling",
    code: "KES",
    symbol: "KSh",
    country: "Kenya",
    flag: "🇰🇪",
    credValue: 0.0067,
    isActive: true,
  },
  {
    id: "44",
    name: "Ghanaian Cedi",
    code: "GHS",
    symbol: "₵",
    country: "Ghana",
    flag: "🇬🇭",
    credValue: 0.082,
    isActive: true,
  },
  {
    id: "45",
    name: "Egyptian Pound",
    code: "EGP",
    symbol: "£",
    country: "Egypt",
    flag: "🇪🇬",
    credValue: 0.02,
    isActive: true,
  },
  {
    id: "46",
    name: "Moroccan Dirham",
    code: "MAD",
    symbol: "د.م.",
    country: "Morocco",
    flag: "🇲🇦",
    credValue: 0.098,
    isActive: true,
  },
  {
    id: "47",
    name: "Tunisian Dinar",
    code: "TND",
    symbol: "د.ت",
    country: "Tunisia",
    flag: "🇹🇳",
    credValue: 0.32,
    isActive: true,
  },
  {
    id: "48",
    name: "Algerian Dinar",
    code: "DZD",
    symbol: "د.ج",
    country: "Algeria",
    flag: "🇩🇿",
    credValue: 0.0075,
    isActive: true,
  },
  {
    id: "49",
    name: "Ethiopian Birr",
    code: "ETB",
    symbol: "Br",
    country: "Ethiopia",
    flag: "🇪🇹",
    credValue: 0.018,
    isActive: true,
  },
  {
    id: "50",
    name: "Ugandan Shilling",
    code: "UGX",
    symbol: "USh",
    country: "Uganda",
    flag: "🇺🇬",
    credValue: 0.00027,
    isActive: true,
  },

  // Latin American Currencies
  {
    id: "51",
    name: "Brazilian Real",
    code: "BRL",
    symbol: "R$",
    country: "Brazil",
    flag: "🇧🇷",
    credValue: 0.2,
    isActive: true,
  },
  {
    id: "52",
    name: "Mexican Peso",
    code: "MXN",
    symbol: "$",
    country: "Mexico",
    flag: "🇲🇽",
    credValue: 0.058,
    isActive: true,
  },
  {
    id: "53",
    name: "Argentine Peso",
    code: "ARS",
    symbol: "$",
    country: "Argentina",
    flag: "🇦🇷",
    credValue: 0.0011,
    isActive: true,
  },
  {
    id: "54",
    name: "Chilean Peso",
    code: "CLP",
    symbol: "$",
    country: "Chile",
    flag: "🇨🇱",
    credValue: 0.0011,
    isActive: true,
  },
  {
    id: "55",
    name: "Colombian Peso",
    code: "COP",
    symbol: "$",
    country: "Colombia",
    flag: "🇨🇴",
    credValue: 0.00025,
    isActive: true,
  },
  {
    id: "56",
    name: "Peruvian Sol",
    code: "PEN",
    symbol: "S/",
    country: "Peru",
    flag: "🇵🇪",
    credValue: 0.27,
    isActive: true,
  },
  {
    id: "57",
    name: "Uruguayan Peso",
    code: "UYU",
    symbol: "$U",
    country: "Uruguay",
    flag: "🇺🇾",
    credValue: 0.026,
    isActive: true,
  },
  {
    id: "58",
    name: "Paraguayan Guarani",
    code: "PYG",
    symbol: "₲",
    country: "Paraguay",
    flag: "🇵🇾",
    credValue: 0.00014,
    isActive: true,
  },
  {
    id: "59",
    name: "Bolivian Boliviano",
    code: "BOB",
    symbol: "Bs",
    country: "Bolivia",
    flag: "🇧🇴",
    credValue: 0.14,
    isActive: true,
  },
  {
    id: "60",
    name: "Venezuelan Bolívar",
    code: "VES",
    symbol: "Bs.S",
    country: "Venezuela",
    flag: "🇻🇪",
    credValue: 0.000028,
    isActive: true,
  },

  // Caribbean Currencies
  {
    id: "61",
    name: "Jamaican Dollar",
    code: "JMD",
    symbol: "J$",
    country: "Jamaica",
    flag: "🇯🇲",
    credValue: 0.0065,
    isActive: true,
  },
  {
    id: "62",
    name: "Barbadian Dollar",
    code: "BBD",
    symbol: "Bds$",
    country: "Barbados",
    flag: "🇧🇧",
    credValue: 0.5,
    isActive: true,
  },
  {
    id: "63",
    name: "Trinidad and Tobago Dollar",
    code: "TTD",
    symbol: "TT$",
    country: "Trinidad and Tobago",
    flag: "🇹🇹",
    credValue: 0.15,
    isActive: true,
  },
  {
    id: "64",
    name: "Bahamian Dollar",
    code: "BSD",
    symbol: "B$",
    country: "Bahamas",
    flag: "🇧🇸",
    credValue: 1.0,
    isActive: true,
  },
  {
    id: "65",
    name: "East Caribbean Dollar",
    code: "XCD",
    symbol: "EC$",
    country: "Eastern Caribbean",
    flag: "🏴",
    credValue: 0.37,
    isActive: true,
  },

  // Pacific Currencies
  {
    id: "66",
    name: "Fijian Dollar",
    code: "FJD",
    symbol: "FJ$",
    country: "Fiji",
    flag: "🇫🇯",
    credValue: 0.45,
    isActive: true,
  },
  {
    id: "67",
    name: "Papua New Guinea Kina",
    code: "PGK",
    symbol: "K",
    country: "Papua New Guinea",
    flag: "🇵🇬",
    credValue: 0.27,
    isActive: true,
  },
  {
    id: "68",
    name: "Vanuatu Vatu",
    code: "VUV",
    symbol: "VT",
    country: "Vanuatu",
    flag: "🇻🇺",
    credValue: 0.0084,
    isActive: true,
  },
  {
    id: "69",
    name: "Samoan Tala",
    code: "WST",
    symbol: "WS$",
    country: "Samoa",
    flag: "🇼🇸",
    credValue: 0.37,
    isActive: true,
  },
  {
    id: "70",
    name: "Tongan Paʻanga",
    code: "TOP",
    symbol: "T$",
    country: "Tonga",
    flag: "🇹🇴",
    credValue: 0.43,
    isActive: true,
  },

  // Additional Asian Currencies
  {
    id: "71",
    name: "Bangladeshi Taka",
    code: "BDT",
    symbol: "৳",
    country: "Bangladesh",
    flag: "🇧🇩",
    credValue: 0.0091,
    isActive: true,
  },
  {
    id: "72",
    name: "Sri Lankan Rupee",
    code: "LKR",
    symbol: "₨",
    country: "Sri Lanka",
    flag: "🇱🇰",
    credValue: 0.0031,
    isActive: true,
  },
  {
    id: "73",
    name: "Nepalese Rupee",
    code: "NPR",
    symbol: "₨",
    country: "Nepal",
    flag: "🇳🇵",
    credValue: 0.0075,
    isActive: true,
  },
  {
    id: "74",
    name: "Maldivian Rufiyaa",
    code: "MVR",
    symbol: "Rf",
    country: "Maldives",
    flag: "🇲🇻",
    credValue: 0.065,
    isActive: true,
  },
  {
    id: "75",
    name: "Bhutanese Ngultrum",
    code: "BTN",
    symbol: "Nu.",
    country: "Bhutan",
    flag: "🇧🇹",
    credValue: 0.012,
    isActive: true,
  },

  // Additional Middle Eastern Currencies
  {
    id: "76",
    name: "Iranian Rial",
    code: "IRR",
    symbol: "﷼",
    country: "Iran",
    flag: "🇮🇷",
    credValue: 0.000024,
    isActive: true,
  },
  {
    id: "77",
    name: "Iraqi Dinar",
    code: "IQD",
    symbol: "ع.د",
    country: "Iraq",
    flag: "🇮🇶",
    credValue: 0.00076,
    isActive: true,
  },
  {
    id: "78",
    name: "Syrian Pound",
    code: "SYP",
    symbol: "£",
    country: "Syria",
    flag: "🇸🇾",
    credValue: 0.0004,
    isActive: true,
  },
  {
    id: "79",
    name: "Yemeni Rial",
    code: "YER",
    symbol: "﷼",
    country: "Yemen",
    flag: "🇾🇪",
    credValue: 0.004,
    isActive: true,
  },
  {
    id: "80",
    name: "Afghan Afghani",
    code: "AFN",
    symbol: "؋",
    country: "Afghanistan",
    flag: "🇦🇫",
    credValue: 0.011,
    isActive: true,
  },

  // Additional European Currencies
  {
    id: "81",
    name: "Ukrainian Hryvnia",
    code: "UAH",
    symbol: "₴",
    country: "Ukraine",
    flag: "🇺🇦",
    credValue: 0.027,
    isActive: true,
  },
  {
    id: "82",
    name: "Belarusian Ruble",
    code: "BYN",
    symbol: "Br",
    country: "Belarus",
    flag: "🇧🇾",
    credValue: 0.31,
    isActive: true,
  },
  {
    id: "83",
    name: "Moldovan Leu",
    code: "MDL",
    symbol: "L",
    country: "Moldova",
    flag: "🇲🇩",
    credValue: 0.055,
    isActive: true,
  },
  {
    id: "84",
    name: "Georgian Lari",
    code: "GEL",
    symbol: "₾",
    country: "Georgia",
    flag: "🇬🇪",
    credValue: 0.37,
    isActive: true,
  },
  {
    id: "85",
    name: "Armenian Dram",
    code: "AMD",
    symbol: "֏",
    country: "Armenia",
    flag: "🇦🇲",
    credValue: 0.0026,
    isActive: true,
  },
  {
    id: "86",
    name: "Azerbaijani Manat",
    code: "AZN",
    symbol: "₼",
    country: "Azerbaijan",
    flag: "🇦🇿",
    credValue: 0.59,
    isActive: true,
  },
  {
    id: "87",
    name: "Kazakhstani Tenge",
    code: "KZT",
    symbol: "₸",
    country: "Kazakhstan",
    flag: "🇰🇿",
    credValue: 0.0022,
    isActive: true,
  },
  {
    id: "88",
    name: "Uzbekistani Som",
    code: "UZS",
    symbol: "лв",
    country: "Uzbekistan",
    flag: "🇺🇿",
    credValue: 0.000088,
    isActive: true,
  },
  {
    id: "89",
    name: "Kyrgyzstani Som",
    code: "KGS",
    symbol: "лв",
    country: "Kyrgyzstan",
    flag: "🇰🇬",
    credValue: 0.011,
    isActive: true,
  },
  {
    id: "90",
    name: "Tajikistani Somoni",
    code: "TJS",
    symbol: "ЅМ",
    country: "Tajikistan",
    flag: "🇹🇯",
    credValue: 0.092,
    isActive: true,
  },

  // Additional African Currencies
  {
    id: "91",
    name: "Botswana Pula",
    code: "BWP",
    symbol: "P",
    country: "Botswana",
    flag: "🇧🇼",
    credValue: 0.074,
    isActive: true,
  },
  {
    id: "92",
    name: "Namibian Dollar",
    code: "NAD",
    symbol: "N$",
    country: "Namibia",
    flag: "🇳🇦",
    credValue: 0.053,
    isActive: true,
  },
  {
    id: "93",
    name: "Zambian Kwacha",
    code: "ZMW",
    symbol: "ZK",
    country: "Zambia",
    flag: "🇿🇲",
    credValue: 0.039,
    isActive: true,
  },
  {
    id: "94",
    name: "Zimbabwean Dollar",
    code: "ZWL",
    symbol: "Z$",
    country: "Zimbabwe",
    flag: "🇿🇼",
    credValue: 0.0028,
    isActive: true,
  },
  {
    id: "95",
    name: "Mozambican Metical",
    code: "MZN",
    symbol: "MT",
    country: "Mozambique",
    flag: "🇲🇿",
    credValue: 0.016,
    isActive: true,
  },
  {
    id: "96",
    name: "Angolan Kwanza",
    code: "AOA",
    symbol: "Kz",
    country: "Angola",
    flag: "🇦🇴",
    credValue: 0.0012,
    isActive: true,
  },
  {
    id: "97",
    name: "Tanzanian Shilling",
    code: "TZS",
    symbol: "TSh",
    country: "Tanzania",
    flag: "🇹🇿",
    credValue: 0.0004,
    isActive: true,
  },
  {
    id: "98",
    name: "Rwandan Franc",
    code: "RWF",
    symbol: "FRw",
    country: "Rwanda",
    flag: "🇷🇼",
    credValue: 0.00082,
    isActive: true,
  },
  {
    id: "99",
    name: "Burundian Franc",
    code: "BIF",
    symbol: "FBu",
    country: "Burundi",
    flag: "🇧🇮",
    credValue: 0.00035,
    isActive: true,
  },
  {
    id: "100",
    name: "Malagasy Ariary",
    code: "MGA",
    symbol: "Ar",
    country: "Madagascar",
    flag: "🇲🇬",
    credValue: 0.00022,
    isActive: true,
  },

  // Additional Currencies (101-180)
  {
    id: "101",
    name: "Mauritanian Ouguiya",
    code: "MRU",
    symbol: "UM",
    country: "Mauritania",
    flag: "🇲🇷",
    credValue: 0.027,
    isActive: true,
  },
  {
    id: "102",
    name: "Gambian Dalasi",
    code: "GMD",
    symbol: "D",
    country: "Gambia",
    flag: "🇬🇲",
    credValue: 0.015,
    isActive: true,
  },
  {
    id: "103",
    name: "Sierra Leonean Leone",
    code: "SLL",
    symbol: "Le",
    country: "Sierra Leone",
    flag: "🇸🇱",
    credValue: 0.000048,
    isActive: true,
  },
  {
    id: "104",
    name: "Liberian Dollar",
    code: "LRD",
    symbol: "L$",
    country: "Liberia",
    flag: "🇱🇷",
    credValue: 0.0053,
    isActive: true,
  },
  {
    id: "105",
    name: "Guinean Franc",
    code: "GNF",
    symbol: "FG",
    country: "Guinea",
    flag: "🇬🇳",
    credValue: 0.00012,
    isActive: true,
  },
  {
    id: "106",
    name: "Cape Verdean Escudo",
    code: "CVE",
    symbol: "$",
    country: "Cape Verde",
    flag: "🇨🇻",
    credValue: 0.0098,
    isActive: true,
  },
  {
    id: "107",
    name: "São Tomé and Príncipe Dobra",
    code: "STN",
    symbol: "Db",
    country: "São Tomé and Príncipe",
    flag: "🇸🇹",
    credValue: 0.045,
    isActive: true,
  },
  {
    id: "108",
    name: "Central African CFA Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "Central Africa",
    flag: "🏴",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "109",
    name: "West African CFA Franc",
    code: "XOF",
    symbol: "CFA",
    country: "West Africa",
    flag: "🏴",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "110",
    name: "Comorian Franc",
    code: "KMF",
    symbol: "CF",
    country: "Comoros",
    flag: "🇰🇲",
    credValue: 0.0022,
    isActive: true,
  },

  // Additional Asian Currencies
  {
    id: "111",
    name: "Cambodian Riel",
    code: "KHR",
    symbol: "៛",
    country: "Cambodia",
    flag: "🇰🇭",
    credValue: 0.00024,
    isActive: true,
  },
  {
    id: "112",
    name: "Laotian Kip",
    code: "LAK",
    symbol: "₭",
    country: "Laos",
    flag: "🇱🇦",
    credValue: 0.000047,
    isActive: true,
  },
  {
    id: "113",
    name: "Myanmar Kyat",
    code: "MMK",
    symbol: "K",
    country: "Myanmar",
    flag: "🇲🇲",
    credValue: 0.00048,
    isActive: true,
  },
  {
    id: "114",
    name: "Brunei Dollar",
    code: "BND",
    symbol: "B$",
    country: "Brunei",
    flag: "🇧🇳",
    credValue: 0.74,
    isActive: true,
  },
  {
    id: "115",
    name: "Mongolian Tugrik",
    code: "MNT",
    symbol: "₮",
    country: "Mongolia",
    flag: "🇲🇳",
    credValue: 0.00037,
    isActive: true,
  },
  {
    id: "116",
    name: "North Korean Won",
    code: "KPW",
    symbol: "₩",
    country: "North Korea",
    flag: "🇰🇵",
    credValue: 0.0011,
    isActive: true,
  },
  {
    id: "117",
    name: "Macanese Pataca",
    code: "MOP",
    symbol: "MOP$",
    country: "Macau",
    flag: "🇲🇴",
    credValue: 0.12,
    isActive: true,
  },
  {
    id: "118",
    name: "Turkmenistani Manat",
    code: "TMT",
    symbol: "T",
    country: "Turkmenistan",
    flag: "🇹🇲",
    credValue: 0.29,
    isActive: true,
  },

  // Additional European Currencies
  {
    id: "119",
    name: "Icelandic Króna",
    code: "ISK",
    symbol: "kr",
    country: "Iceland",
    flag: "🇮🇸",
    credValue: 0.0072,
    isActive: true,
  },
  {
    id: "120",
    name: "Faroese Króna",
    code: "FOK",
    symbol: "kr",
    country: "Faroe Islands",
    flag: "🇫🇴",
    credValue: 0.14,
    isActive: true,
  },
  {
    id: "121",
    name: "Gibraltar Pound",
    code: "GIP",
    symbol: "£",
    country: "Gibraltar",
    flag: "🇬🇮",
    credValue: 1.27,
    isActive: true,
  },
  {
    id: "122",
    name: "Guernsey Pound",
    code: "GGP",
    symbol: "£",
    country: "Guernsey",
    flag: "🇬🇬",
    credValue: 1.27,
    isActive: true,
  },
  {
    id: "123",
    name: "Jersey Pound",
    code: "JEP",
    symbol: "£",
    country: "Jersey",
    flag: "🇯🇪",
    credValue: 1.27,
    isActive: true,
  },
  {
    id: "124",
    name: "Isle of Man Pound",
    code: "IMP",
    symbol: "£",
    country: "Isle of Man",
    flag: "🇮🇲",
    credValue: 1.27,
    isActive: true,
  },
  {
    id: "125",
    name: "Serbian Dinar",
    code: "RSD",
    symbol: "Дин.",
    country: "Serbia",
    flag: "🇷🇸",
    credValue: 0.0091,
    isActive: true,
  },
  {
    id: "126",
    name: "Bosnian Convertible Mark",
    code: "BAM",
    symbol: "KM",
    country: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    credValue: 0.55,
    isActive: true,
  },
  {
    id: "127",
    name: "North Macedonian Denar",
    code: "MKD",
    symbol: "ден",
    country: "North Macedonia",
    flag: "🇲🇰",
    credValue: 0.018,
    isActive: true,
  },
  {
    id: "128",
    name: "Albanian Lek",
    code: "ALL",
    symbol: "L",
    country: "Albania",
    flag: "🇦🇱",
    credValue: 0.011,
    isActive: true,
  },
  {
    id: "129",
    name: "Montenegrin Euro",
    code: "EUR",
    symbol: "€",
    country: "Montenegro",
    flag: "🇲🇪",
    credValue: 1.08,
    isActive: true,
  },
  {
    id: "130",
    name: "Kosovar Euro",
    code: "EUR",
    symbol: "€",
    country: "Kosovo",
    flag: "🇽🇰",
    credValue: 1.08,
    isActive: true,
  },

  // Additional Pacific Currencies
  {
    id: "131",
    name: "Solomon Islands Dollar",
    code: "SBD",
    symbol: "SI$",
    country: "Solomon Islands",
    flag: "🇸🇧",
    credValue: 0.12,
    isActive: true,
  },
  {
    id: "132",
    name: "Kiribati Dollar",
    code: "AUD",
    symbol: "A$",
    country: "Kiribati",
    flag: "🇰🇮",
    credValue: 0.65,
    isActive: true,
  },
  {
    id: "133",
    name: "Tuvaluan Dollar",
    code: "AUD",
    symbol: "A$",
    country: "Tuvalu",
    flag: "🇹🇻",
    credValue: 0.65,
    isActive: true,
  },
  {
    id: "134",
    name: "Nauruan Dollar",
    code: "AUD",
    symbol: "A$",
    country: "Nauru",
    flag: "🇳🇷",
    credValue: 0.65,
    isActive: true,
  },
  {
    id: "135",
    name: "Palauan Dollar",
    code: "USD",
    symbol: "$",
    country: "Palau",
    flag: "🇵🇼",
    credValue: 1.0,
    isActive: true,
  },
  {
    id: "136",
    name: "Marshallese Dollar",
    code: "USD",
    symbol: "$",
    country: "Marshall Islands",
    flag: "🇲🇭",
    credValue: 1.0,
    isActive: true,
  },
  {
    id: "137",
    name: "Micronesian Dollar",
    code: "USD",
    symbol: "$",
    country: "Micronesia",
    flag: "🇫🇲",
    credValue: 1.0,
    isActive: true,
  },
  {
    id: "138",
    name: "Cook Islands Dollar",
    code: "NZD",
    symbol: "NZ$",
    country: "Cook Islands",
    flag: "🇨🇰",
    credValue: 0.6,
    isActive: true,
  },
  {
    id: "139",
    name: "Niuean Dollar",
    code: "NZD",
    symbol: "NZ$",
    country: "Niue",
    flag: "🇳🇺",
    credValue: 0.6,
    isActive: true,
  },
  {
    id: "140",
    name: "Tokelauan Dollar",
    code: "NZD",
    symbol: "NZ$",
    country: "Tokelau",
    flag: "🇹🇰",
    credValue: 0.6,
    isActive: true,
  },

  // Additional Caribbean Currencies
  {
    id: "141",
    name: "Cuban Peso",
    code: "CUP",
    symbol: "₱",
    country: "Cuba",
    flag: "🇨🇺",
    credValue: 0.042,
    isActive: true,
  },
  {
    id: "142",
    name: "Dominican Peso",
    code: "DOP",
    symbol: "RD$",
    country: "Dominican Republic",
    flag: "🇩🇴",
    credValue: 0.018,
    isActive: true,
  },
  {
    id: "143",
    name: "Haitian Gourde",
    code: "HTG",
    symbol: "G",
    country: "Haiti",
    flag: "🇭🇹",
    credValue: 0.0076,
    isActive: true,
  },
  {
    id: "144",
    name: "Netherlands Antillean Guilder",
    code: "ANG",
    symbol: "ƒ",
    country: "Curaçao & Sint Maarten",
    flag: "🇨🇼",
    credValue: 0.56,
    isActive: true,
  },
  {
    id: "145",
    name: "Aruban Florin",
    code: "AWG",
    symbol: "ƒ",
    country: "Aruba",
    flag: "🇦🇼",
    credValue: 0.56,
    isActive: true,
  },
  {
    id: "146",
    name: "Cayman Islands Dollar",
    code: "KYD",
    symbol: "CI$",
    country: "Cayman Islands",
    flag: "🇰🇾",
    credValue: 1.2,
    isActive: true,
  },
  {
    id: "147",
    name: "Bermudian Dollar",
    code: "BMD",
    symbol: "BD$",
    country: "Bermuda",
    flag: "🇧🇲",
    credValue: 1.0,
    isActive: true,
  },

  // Additional South American Currencies
  {
    id: "148",
    name: "Guyanese Dollar",
    code: "GYD",
    symbol: "G$",
    country: "Guyana",
    flag: "🇬🇾",
    credValue: 0.0048,
    isActive: true,
  },
  {
    id: "149",
    name: "Surinamese Dollar",
    code: "SRD",
    symbol: "Sr$",
    country: "Suriname",
    flag: "🇸🇷",
    credValue: 0.028,
    isActive: true,
  },
  {
    id: "150",
    name: "French Guianan Euro",
    code: "EUR",
    symbol: "€",
    country: "French Guiana",
    flag: "🇬🇫",
    credValue: 1.08,
    isActive: true,
  },
  {
    id: "151",
    name: "Falkland Islands Pound",
    code: "FKP",
    symbol: "£",
    country: "Falkland Islands",
    flag: "🇫🇰",
    credValue: 1.27,
    isActive: true,
  },

  // Additional Oceania Currencies
  {
    id: "152",
    name: "New Caledonian Franc",
    code: "XPF",
    symbol: "₣",
    country: "New Caledonia",
    flag: "🇳🇨",
    credValue: 0.0089,
    isActive: true,
  },
  {
    id: "153",
    name: "French Polynesian Franc",
    code: "XPF",
    symbol: "₣",
    country: "French Polynesia",
    flag: "🇵🇫",
    credValue: 0.0089,
    isActive: true,
  },
  {
    id: "154",
    name: "Wallis and Futuna Franc",
    code: "XPF",
    symbol: "₣",
    country: "Wallis and Futuna",
    flag: "🇼🇫",
    credValue: 0.0089,
    isActive: true,
  },

  // Additional African Island Currencies
  {
    id: "155",
    name: "Seychellois Rupee",
    code: "SCR",
    symbol: "₨",
    country: "Seychelles",
    flag: "🇸🇨",
    credValue: 0.074,
    isActive: true,
  },
  {
    id: "156",
    name: "Mauritian Rupee",
    code: "MUR",
    symbol: "₨",
    country: "Mauritius",
    flag: "🇲🇺",
    credValue: 0.022,
    isActive: true,
  },

  // Additional Middle Eastern/Asian Currencies
  {
    id: "157",
    name: "Myanma Kyat",
    code: "MMK",
    symbol: "K",
    country: "Myanmar",
    flag: "🇲🇲",
    credValue: 0.00048,
    isActive: true,
  },
  {
    id: "158",
    name: "East Timorese Dollar",
    code: "USD",
    symbol: "$",
    country: "East Timor",
    flag: "🇹🇱",
    credValue: 1.0,
    isActive: true,
  },

  // Special Administrative Regions
  {
    id: "159",
    name: "Hong Kong Dollar",
    code: "HKD",
    symbol: "HK$",
    country: "Hong Kong SAR",
    flag: "🇭🇰",
    credValue: 0.13,
    isActive: true,
  },
  {
    id: "160",
    name: "Macanese Pataca",
    code: "MOP",
    symbol: "MOP$",
    country: "Macau SAR",
    flag: "🇲🇴",
    credValue: 0.12,
    isActive: true,
  },

  // Additional European Dependencies
  {
    id: "161",
    name: "Saint Helena Pound",
    code: "SHP",
    symbol: "£",
    country: "Saint Helena",
    flag: "🇸🇭",
    credValue: 1.27,
    isActive: true,
  },
  {
    id: "162",
    name: "Ascension Island Pound",
    code: "SHP",
    symbol: "£",
    country: "Ascension Island",
    flag: "🇦🇨",
    credValue: 1.27,
    isActive: true,
  },
  {
    id: "163",
    name: "Tristan da Cunha Pound",
    code: "SHP",
    symbol: "£",
    country: "Tristan da Cunha",
    flag: "🇹🇦",
    credValue: 1.27,
    isActive: true,
  },

  // Additional Currencies to reach 180
  {
    id: "164",
    name: "Lesotho Loti",
    code: "LSL",
    symbol: "L",
    country: "Lesotho",
    flag: "🇱🇸",
    credValue: 0.053,
    isActive: true,
  },
  {
    id: "165",
    name: "Swazi Lilangeni",
    code: "SZL",
    symbol: "E",
    country: "Eswatini",
    flag: "🇸🇿",
    credValue: 0.053,
    isActive: true,
  },
  {
    id: "166",
    name: "Djiboutian Franc",
    code: "DJF",
    symbol: "Fdj",
    country: "Djibouti",
    flag: "🇩🇯",
    credValue: 0.0056,
    isActive: true,
  },
  {
    id: "167",
    name: "Eritrean Nakfa",
    code: "ERN",
    symbol: "Nfk",
    country: "Eritrea",
    flag: "🇪🇷",
    credValue: 0.067,
    isActive: true,
  },
  {
    id: "168",
    name: "Somali Shilling",
    code: "SOS",
    symbol: "S",
    country: "Somalia",
    flag: "🇸🇴",
    credValue: 0.0017,
    isActive: true,
  },
  {
    id: "169",
    name: "South Sudanese Pound",
    code: "SSP",
    symbol: "£",
    country: "South Sudan",
    flag: "🇸🇸",
    credValue: 0.0077,
    isActive: true,
  },
  {
    id: "170",
    name: "Sudanese Pound",
    code: "SDG",
    symbol: "ج.س.",
    country: "Sudan",
    flag: "🇸🇩",
    credValue: 0.0017,
    isActive: true,
  },
  {
    id: "171",
    name: "Libyan Dinar",
    code: "LYD",
    symbol: "ل.د",
    country: "Libya",
    flag: "🇱🇾",
    credValue: 0.21,
    isActive: true,
  },
  {
    id: "172",
    name: "Chadian Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "Chad",
    flag: "🇹🇩",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "173",
    name: "Central African Republic Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "Central African Republic",
    flag: "🇨🇫",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "174",
    name: "Equatorial Guinean Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "Equatorial Guinea",
    flag: "🇬🇶",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "175",
    name: "Gabonese Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "Gabon",
    flag: "🇬🇦",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "176",
    name: "Cameroonian Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "Cameroon",
    flag: "🇨🇲",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "177",
    name: "Republic of the Congo Franc",
    code: "XAF",
    symbol: "FCFA",
    country: "Republic of the Congo",
    flag: "🇨🇬",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "178",
    name: "Democratic Republic of the Congo Franc",
    code: "CDF",
    symbol: "FC",
    country: "Democratic Republic of the Congo",
    flag: "🇨🇩",
    credValue: 0.0004,
    isActive: true,
  },
  {
    id: "179",
    name: "Beninese Franc",
    code: "XOF",
    symbol: "CFA",
    country: "Benin",
    flag: "🇧🇯",
    credValue: 0.0016,
    isActive: true,
  },
  {
    id: "180",
    name: "Credon",
    code: "CRED",
    symbol: "₡",
    country: "Heavenslive",
    flag: "🌟",
    credValue: 1.0,
    isActive: true,
  },
]

export const getCurrencyByCode = (code: string): Currency | undefined => {
  return currencies.find((currency) => currency.code === code)
}

export const convertCurrency = (amount: number, fromCode: string, toCode: string): number => {
  const fromCurrency = getCurrencyByCode(fromCode)
  const toCurrency = getCurrencyByCode(toCode)

  if (!fromCurrency || !toCurrency) {
    throw new Error("Currency not found")
  }

  // Convert to CRED first, then to target currency
  const credAmount = amount * fromCurrency.credValue
  return credAmount / toCurrency.credValue
}
