-- Create comprehensive global currencies table
CREATE TABLE IF NOT EXISTS global_currencies (
  id SERIAL PRIMARY KEY,
  country_code VARCHAR(3) NOT NULL UNIQUE,
  country_name VARCHAR(100) NOT NULL,
  currency_code VARCHAR(3) NOT NULL,
  currency_name VARCHAR(100) NOT NULL,
  currency_symbol VARCHAR(10),
  cred_parity_rate DECIMAL(15,8) NOT NULL DEFAULT 1.0,
  is_active BOOLEAN DEFAULT true,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert all 195+ countries and their currencies
INSERT INTO global_currencies (country_code, country_name, currency_code, currency_name, currency_symbol, cred_parity_rate) VALUES
-- Major Economies
('USA', 'United States', 'USD', 'US Dollar', '$', 1.0),
('EUR', 'Eurozone', 'EUR', 'Euro', '€', 0.85),
('GBR', 'United Kingdom', 'GBP', 'British Pound', '£', 0.75),
('JPN', 'Japan', 'JPY', 'Japanese Yen', '¥', 150.0),
('CHN', 'China', 'CNY', 'Chinese Yuan', '¥', 7.2),
('IND', 'India', 'INR', 'Indian Rupee', '₹', 83.0),
('CAN', 'Canada', 'CAD', 'Canadian Dollar', 'C$', 1.35),
('AUS', 'Australia', 'AUD', 'Australian Dollar', 'A$', 1.55),
('CHE', 'Switzerland', 'CHF', 'Swiss Franc', 'Fr', 0.90),
('KOR', 'South Korea', 'KRW', 'South Korean Won', '₩', 1300.0),

-- Africa
('DZA', 'Algeria', 'DZD', 'Algerian Dinar', 'د.ج', 134.0),
('AGO', 'Angola', 'AOA', 'Angolan Kwanza', 'Kz', 825.0),
('BEN', 'Benin', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('BWA', 'Botswana', 'BWP', 'Botswana Pula', 'P', 13.5),
('BFA', 'Burkina Faso', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('BDI', 'Burundi', 'BIF', 'Burundian Franc', 'Fr', 2800.0),
('CMR', 'Cameroon', 'XAF', 'Central African CFA Franc', 'Fr', 600.0),
('CPV', 'Cape Verde', 'CVE', 'Cape Verdean Escudo', '$', 100.0),
('CAF', 'Central African Republic', 'XAF', 'Central African CFA Franc', 'Fr', 600.0),
('TCD', 'Chad', 'XAF', 'Central African CFA Franc', 'Fr', 600.0),
('COM', 'Comoros', 'KMF', 'Comorian Franc', 'Fr', 450.0),
('COG', 'Republic of the Congo', 'XAF', 'Central African CFA Franc', 'Fr', 600.0),
('COD', 'Democratic Republic of the Congo', 'CDF', 'Congolese Franc', 'Fr', 2500.0),
('CIV', 'Côte d''Ivoire', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('DJI', 'Djibouti', 'DJF', 'Djiboutian Franc', 'Fr', 178.0),
('EGY', 'Egypt', 'EGP', 'Egyptian Pound', '£', 31.0),
('GNQ', 'Equatorial Guinea', 'XAF', 'Central African CFA Franc', 'Fr', 600.0),
('ERI', 'Eritrea', 'ERN', 'Eritrean Nakfa', 'Nfk', 15.0),
('SWZ', 'Eswatini', 'SZL', 'Swazi Lilangeni', 'L', 18.5),
('ETH', 'Ethiopia', 'ETB', 'Ethiopian Birr', 'Br', 55.0),
('GAB', 'Gabon', 'XAF', 'Central African CFA Franc', 'Fr', 600.0),
('GMB', 'Gambia', 'GMD', 'Gambian Dalasi', 'D', 65.0),
('GHA', 'Ghana', 'GHS', 'Ghanaian Cedi', '₵', 12.0),
('GIN', 'Guinea', 'GNF', 'Guinean Franc', 'Fr', 8500.0),
('GNB', 'Guinea-Bissau', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('KEN', 'Kenya', 'KES', 'Kenyan Shilling', 'Sh', 150.0),
('LSO', 'Lesotho', 'LSL', 'Lesotho Loti', 'L', 18.5),
('LBR', 'Liberia', 'LRD', 'Liberian Dollar', 'L$', 185.0),
('LBY', 'Libya', 'LYD', 'Libyan Dinar', 'ل.د', 4.8),
('MDG', 'Madagascar', 'MGA', 'Malagasy Ariary', 'Ar', 4500.0),
('MWI', 'Malawi', 'MWK', 'Malawian Kwacha', 'MK', 1700.0),
('MLI', 'Mali', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('MRT', 'Mauritania', 'MRU', 'Mauritanian Ouguiya', 'UM', 37.0),
('MUS', 'Mauritius', 'MUR', 'Mauritian Rupee', '₨', 45.0),
('MAR', 'Morocco', 'MAD', 'Moroccan Dirham', 'د.م.', 10.0),
('MOZ', 'Mozambique', 'MZN', 'Mozambican Metical', 'MT', 64.0),
('NAM', 'Namibia', 'NAD', 'Namibian Dollar', 'N$', 18.5),
('NER', 'Niger', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('NGA', 'Nigeria', 'NGN', 'Nigerian Naira', '₦', 800.0),
('RWA', 'Rwanda', 'RWF', 'Rwandan Franc', 'Fr', 1200.0),
('STP', 'São Tomé and Príncipe', 'STN', 'São Tomé and Príncipe Dobra', 'Db', 22.0),
('SEN', 'Senegal', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('SYC', 'Seychelles', 'SCR', 'Seychellois Rupee', '₨', 13.5),
('SLE', 'Sierra Leone', 'SLL', 'Sierra Leonean Leone', 'Le', 20000.0),
('SOM', 'Somalia', 'SOS', 'Somali Shilling', 'Sh', 570.0),
('ZAF', 'South Africa', 'ZAR', 'South African Rand', 'R', 18.5),
('SSD', 'South Sudan', 'SSP', 'South Sudanese Pound', '£', 1300.0),
('SDN', 'Sudan', 'SDG', 'Sudanese Pound', 'ج.س.', 600.0),
('TZA', 'Tanzania', 'TZS', 'Tanzanian Shilling', 'Sh', 2500.0),
('TGO', 'Togo', 'XOF', 'West African CFA Franc', 'Fr', 600.0),
('TUN', 'Tunisia', 'TND', 'Tunisian Dinar', 'د.ت', 3.1),
('UGA', 'Uganda', 'UGX', 'Ugandan Shilling', 'Sh', 3700.0),
('ZMB', 'Zambia', 'ZMW', 'Zambian Kwacha', 'ZK', 25.0),
('ZWE', 'Zimbabwe', 'ZWL', 'Zimbabwean Dollar', 'Z$', 320.0),

-- Asia
('AFG', 'Afghanistan', 'AFN', 'Afghan Afghani', '؋', 75.0),
('ARM', 'Armenia', 'AMD', 'Armenian Dram', '֏', 400.0),
('AZE', 'Azerbaijan', 'AZN', 'Azerbaijani Manat', '₼', 1.7),
('BHR', 'Bahrain', 'BHD', 'Bahraini Dinar', '.د.ب', 0.38),
('BGD', 'Bangladesh', 'BDT', 'Bangladeshi Taka', '৳', 110.0),
('BTN', 'Bhutan', 'BTN', 'Bhutanese Ngultrum', 'Nu.', 83.0),
('BRN', 'Brunei', 'BND', 'Brunei Dollar', 'B$', 1.35),
('KHM', 'Cambodia', 'KHR', 'Cambodian Riel', '៛', 4100.0),
('GEO', 'Georgia', 'GEL', 'Georgian Lari', '₾', 2.7),
('IDN', 'Indonesia', 'IDR', 'Indonesian Rupiah', 'Rp', 15500.0),
('IRN', 'Iran', 'IRR', 'Iranian Rial', '﷼', 42000.0),
('IRQ', 'Iraq', 'IQD', 'Iraqi Dinar', 'ع.د', 1310.0),
('ISR', 'Israel', 'ILS', 'Israeli New Shekel', '₪', 3.7),
('JOR', 'Jordan', 'JOD', 'Jordanian Dinar', 'د.ا', 0.71),
('KAZ', 'Kazakhstan', 'KZT', 'Kazakhstani Tenge', '₸', 450.0),
('KWT', 'Kuwait', 'KWD', 'Kuwaiti Dinar', 'د.ك', 0.31),
('KGZ', 'Kyrgyzstan', 'KGS', 'Kyrgyzstani Som', 'с', 89.0),
('LAO', 'Laos', 'LAK', 'Lao Kip', '₭', 20000.0),
('LBN', 'Lebanon', 'LBP', 'Lebanese Pound', 'ل.ل', 89500.0),
('MYS', 'Malaysia', 'MYR', 'Malaysian Ringgit', 'RM', 4.7),
('MDV', 'Maldives', 'MVR', 'Maldivian Rufiyaa', '.ރ', 15.4),
('MNG', 'Mongolia', 'MNT', 'Mongolian Tugrik', '₮', 3400.0),
('MMR', 'Myanmar', 'MMK', 'Myanmar Kyat', 'Ks', 2100.0),
('NPL', 'Nepal', 'NPR', 'Nepalese Rupee', '₨', 133.0),
('PRK', 'North Korea', 'KPW', 'North Korean Won', '₩', 900.0),
('OMN', 'Oman', 'OMR', 'Omani Rial', 'ر.ع.', 0.38),
('PAK', 'Pakistan', 'PKR', 'Pakistani Rupee', '₨', 280.0),
('PHL', 'Philippines', 'PHP', 'Philippine Peso', '₱', 56.0),
('QAT', 'Qatar', 'QAR', 'Qatari Riyal', 'ر.ق', 3.64),
('SAU', 'Saudi Arabia', 'SAR', 'Saudi Riyal', 'ر.س', 3.75),
('SGP', 'Singapore', 'SGD', 'Singapore Dollar', 'S$', 1.35),
('LKA', 'Sri Lanka', 'LKR', 'Sri Lankan Rupee', '₨', 320.0),
('SYR', 'Syria', 'SYP', 'Syrian Pound', 'ل.س', 2500.0),
('TWN', 'Taiwan', 'TWD', 'New Taiwan Dollar', 'NT$', 31.5),
('TJK', 'Tajikistan', 'TJS', 'Tajikistani Somoni', 'ЅМ', 11.0),
('THA', 'Thailand', 'THB', 'Thai Baht', '฿', 36.0),
('TLS', 'Timor-Leste', 'USD', 'US Dollar', '$', 1.0),
('TUR', 'Turkey', 'TRY', 'Turkish Lira', '₺', 29.0),
('TKM', 'Turkmenistan', 'TMT', 'Turkmenistani Manat', 'm', 3.5),
('ARE', 'United Arab Emirates', 'AED', 'UAE Dirham', 'د.إ', 3.67),
('UZB', 'Uzbekistan', 'UZS', 'Uzbekistani Som', 'сўм', 12200.0),
('VNM', 'Vietnam', 'VND', 'Vietnamese Dong', '₫', 24000.0),
('YEM', 'Yemen', 'YER', 'Yemeni Rial', '﷼', 250.0),

-- Europe
('ALB', 'Albania', 'ALL', 'Albanian Lek', 'L', 95.0),
('AND', 'Andorra', 'EUR', 'Euro', '€', 0.85),
('AUT', 'Austria', 'EUR', 'Euro', '€', 0.85),
('BLR', 'Belarus', 'BYN', 'Belarusian Ruble', 'Br', 3.2),
('BEL', 'Belgium', 'EUR', 'Euro', '€', 0.85),
('BIH', 'Bosnia and Herzegovina', 'BAM', 'Bosnia and Herzegovina Convertible Mark', 'КМ', 1.8),
('BGR', 'Bulgaria', 'BGN', 'Bulgarian Lev', 'лв', 1.8),
('HRV', 'Croatia', 'EUR', 'Euro', '€', 0.85),
('CYP', 'Cyprus', 'EUR', 'Euro', '€', 0.85),
('CZE', 'Czech Republic', 'CZK', 'Czech Koruna', 'Kč', 23.0),
('DNK', 'Denmark', 'DKK', 'Danish Krone', 'kr', 6.8),
('EST', 'Estonia', 'EUR', 'Euro', '€', 0.85),
('FIN', 'Finland', 'EUR', 'Euro', '€', 0.85),
('FRA', 'France', 'EUR', 'Euro', '€', 0.85),
('DEU', 'Germany', 'EUR', 'Euro', '€', 0.85),
('GRC', 'Greece', 'EUR', 'Euro', '€', 0.85),
('HUN', 'Hungary', 'HUF', 'Hungarian Forint', 'Ft', 360.0),
('ISL', 'Iceland', 'ISK', 'Icelandic Krona', 'kr', 140.0),
('IRL', 'Ireland', 'EUR', 'Euro', '€', 0.85),
('ITA', 'Italy', 'EUR', 'Euro', '€', 0.85),
('XKX', 'Kosovo', 'EUR', 'Euro', '€', 0.85),
('LVA', 'Latvia', 'EUR', 'Euro', '€', 0.85),
('LIE', 'Liechtenstein', 'CHF', 'Swiss Franc', 'Fr', 0.90),
('LTU', 'Lithuania', 'EUR', 'Euro', '€', 0.85),
('LUX', 'Luxembourg', 'EUR', 'Euro', '€', 0.85),
('MLT', 'Malta', 'EUR', 'Euro', '€', 0.85),
('MDA', 'Moldova', 'MDL', 'Moldovan Leu', 'L', 18.0),
('MCO', 'Monaco', 'EUR', 'Euro', '€', 0.85),
('MNE', 'Montenegro', 'EUR', 'Euro', '€', 0.85),
('NLD', 'Netherlands', 'EUR', 'Euro', '€', 0.85),
('MKD', 'North Macedonia', 'MKD', 'Macedonian Denar', 'ден', 56.0),
('NOR', 'Norway', 'NOK', 'Norwegian Krone', 'kr', 10.5),
('POL', 'Poland', 'PLN', 'Polish Zloty', 'zł', 4.0),
('PRT', 'Portugal', 'EUR', 'Euro', '€', 0.85),
('ROU', 'Romania', 'RON', 'Romanian Leu', 'lei', 4.9),
('RUS', 'Russia', 'RUB', 'Russian Ruble', '₽', 90.0),
('SMR', 'San Marino', 'EUR', 'Euro', '€', 0.85),
('SRB', 'Serbia', 'RSD', 'Serbian Dinar', 'дин', 107.0),
('SVK', 'Slovakia', 'EUR', 'Euro', '€', 0.85),
('SVN', 'Slovenia', 'EUR', 'Euro', '€', 0.85),
('ESP', 'Spain', 'EUR', 'Euro', '€', 0.85),
('SWE', 'Sweden', 'SEK', 'Swedish Krona', 'kr', 10.8),
('UKR', 'Ukraine', 'UAH', 'Ukrainian Hryvnia', '₴', 37.0),
('VAT', 'Vatican City', 'EUR', 'Euro', '€', 0.85),

-- North America
('ATG', 'Antigua and Barbuda', 'XCD', 'East Caribbean Dollar', '$', 2.7),
('BHS', 'Bahamas', 'BSD', 'Bahamian Dollar', 'B$', 1.0),
('BRB', 'Barbados', 'BBD', 'Barbadian Dollar', 'Bds$', 2.0),
('BLZ', 'Belize', 'BZD', 'Belize Dollar', 'BZ$', 2.0),
('CRI', 'Costa Rica', 'CRC', 'Costa Rican Colón', '₡', 540.0),
('CUB', 'Cuba', 'CUP', 'Cuban Peso', '$', 24.0),
('DMA', 'Dominica', 'XCD', 'East Caribbean Dollar', '$', 2.7),
('DOM', 'Dominican Republic', 'DOP', 'Dominican Peso', 'RD$', 57.0),
('SLV', 'El Salvador', 'USD', 'US Dollar', '$', 1.0),
('GRD', 'Grenada', 'XCD', 'East Caribbean Dollar', '$', 2.7),
('GTM', 'Guatemala', 'GTQ', 'Guatemalan Quetzal', 'Q', 7.8),
('HTI', 'Haiti', 'HTG', 'Haitian Gourde', 'G', 150.0),
('HND', 'Honduras', 'HNL', 'Honduran Lempira', 'L', 24.5),
('JAM', 'Jamaica', 'JMD', 'Jamaican Dollar', 'J$', 155.0),
('MEX', 'Mexico', 'MXN', 'Mexican Peso', '$', 17.0),
('NIC', 'Nicaragua', 'NIO', 'Nicaraguan Córdoba', 'C$', 36.5),
('PAN', 'Panama', 'PAB', 'Panamanian Balboa', 'B/.', 1.0),
('KNA', 'Saint Kitts and Nevis', 'XCD', 'East Caribbean Dollar', '$', 2.7),
('LCA', 'Saint Lucia', 'XCD', 'East Caribbean Dollar', '$', 2.7),
('VCT', 'Saint Vincent and the Grenadines', 'XCD', 'East Caribbean Dollar', '$', 2.7),
('TTO', 'Trinidad and Tobago', 'TTD', 'Trinidad and Tobago Dollar', 'TT$', 6.8),

-- South America
('ARG', 'Argentina', 'ARS', 'Argentine Peso', '$', 350.0),
('BOL', 'Bolivia', 'BOB', 'Bolivian Boliviano', 'Bs.', 6.9),
('BRA', 'Brazil', 'BRL', 'Brazilian Real', 'R$', 5.0),
('CHL', 'Chile', 'CLP', 'Chilean Peso', '$', 900.0),
('COL', 'Colombia', 'COP', 'Colombian Peso', '$', 4000.0),
('ECU', 'Ecuador', 'USD', 'US Dollar', '$', 1.0),
('GUY', 'Guyana', 'GYD', 'Guyanese Dollar', 'G$', 210.0),
('PRY', 'Paraguay', 'PYG', 'Paraguayan Guaraní', '₲', 7300.0),
('PER', 'Peru', 'PEN', 'Peruvian Sol', 'S/', 3.7),
('SUR', 'Suriname', 'SRD', 'Surinamese Dollar', 'Sr$', 36.0),
('URY', 'Uruguay', 'UYU', 'Uruguayan Peso', '$U', 39.0),
('VEN', 'Venezuela', 'VES', 'Venezuelan Bolívar', 'Bs.S', 36.0),

-- Oceania
('FJI', 'Fiji', 'FJD', 'Fijian Dollar', 'FJ$', 2.2),
('KIR', 'Kiribati', 'AUD', 'Australian Dollar', 'A$', 1.55),
('MHL', 'Marshall Islands', 'USD', 'US Dollar', '$', 1.0),
('FSM', 'Micronesia', 'USD', 'US Dollar', '$', 1.0),
('NRU', 'Nauru', 'AUD', 'Australian Dollar', 'A$', 1.55),
('NZL', 'New Zealand', 'NZD', 'New Zealand Dollar', 'NZ$', 1.65),
('PLW', 'Palau', 'USD', 'US Dollar', '$', 1.0),
('PNG', 'Papua New Guinea', 'PGK', 'Papua New Guinean Kina', 'K', 3.7),
('WSM', 'Samoa', 'WST', 'Samoan Tala', 'T', 2.7),
('SLB', 'Solomon Islands', 'SBD', 'Solomon Islands Dollar', 'SI$', 8.3),
('TON', 'Tonga', 'TOP', 'Tongan Paʻanga', 'T$', 2.3),
('TUV', 'Tuvalu', 'AUD', 'Australian Dollar', 'A$', 1.55),
('VUT', 'Vanuatu', 'VUV', 'Vanuatu Vatu', 'Vt', 120.0);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_global_currencies_country_code ON global_currencies(country_code);
CREATE INDEX IF NOT EXISTS idx_global_currencies_currency_code ON global_currencies(currency_code);
CREATE INDEX IF NOT EXISTS idx_global_currencies_active ON global_currencies(is_active);

-- Create function to update parity rates
CREATE OR REPLACE FUNCTION update_currency_parity_rate(
  p_country_code VARCHAR(3),
  p_new_rate DECIMAL(15,8)
) RETURNS BOOLEAN AS $$
BEGIN
  UPDATE global_currencies 
  SET cred_parity_rate = p_new_rate,
      last_updated = CURRENT_TIMESTAMP
  WHERE country_code = p_country_code;
  
  RETURN FOUND;
END;
$$ LANGUAGE plpgsql;

-- Create view for active currencies
CREATE OR REPLACE VIEW active_currencies AS
SELECT 
  country_code,
  country_name,
  currency_code,
  currency_name,
  currency_symbol,
  cred_parity_rate,
  CONCAT(currency_code, '-CRED') as cred_pair_code
FROM global_currencies 
WHERE is_active = true
ORDER BY country_name;
